version: 2.1

jobs:
  build:
    docker:
      - image: tylerjw/circle_ci_test-melodic:0.0.1
    environment:
      TEST_VAL: bla  
    steps:
      # Checkout repo
      - restore_cache:
          name: Restoring Cache source-v1
          keys:
            - source-v1-{{ .Revision }}
            - source-v1-
      - checkout:
          path: ~/ws_target/src/circle_ci_test
      - save_cache:
          name: Saving Cache source-v1
          key: source-v1-{{ .Revision }}
          paths:
            - ~/ws_target/src/circle_ci_test/.git

      # Prepare Upstream Workspace
      - restore_cache:
          name: Restoring Cache upstream_ws-v1
          keys:
            - upstream_ws-v1-{{ checksum ~/ws_target/src/circle_ci_test/upstream.rosinstall }}-{{ .Revision }}
            - upstream_ws-v1-{{ checksum ~/ws_target/src/circle_ci_test/upstream.rosinstall }}-
      - run:
          name: Prepare Upstream Workspace
          command: |
            mkdir -p ~/ws_upstream/src
            wstool init 
            vcs import ~/ws_upstream/src --shallow --force --input ~/ws_target/src/circle_ci_test/upstream.rosinstall
            echo $TEST_VAL
      - save_cache:
          name: Saving Cache upstream_ws-v1
          key: upstream_ws-v1-{{ checksum "~/ws_target/src/circle_ci_test/upstream.rosinstall" }}-{{ .Revision }}
          paths:
            - ~/ws_upstream/src

      - run:
          name: Install Upstream Dependencies
          command: rosdep install -q -y --from-paths ~/ws_upstream/src --ignore-src

      - run:
          name: Build Upstream Workspace
          working_directory: ~/ws_upstream
          command: |
            catkin config --install --extends /opt/ros/$ROS_DISTRO \
              --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE=-O3 --
            catkin build --no-status --summarize
