version: 2.1

jobs:
  build:
    docker:
      - image: tylerjw/circle_ci_test-melodic:0.0.1
    environment:
      UPSTREAM_ROSINSTALL: upstream.rosinstall
    working_directory: ~/ws_target
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - checkout:
          path: src/circle_ci_test
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "src/circle_ci_test/.git"


      - restore_cache:
          keys:
            - upstream_ws-v1-{{ .Branch }}-{{ .Revision }}
            - upstream_ws-v1-{{ .Branch }}-
            - upstream_ws-v1-
      - run:
          name: Checkout Upstream Workspace
          command: |
            mkdir -p ~/ws_upstream/src
            vcs import ~/ws_upstream/src --shallow --force --input src/circle_ci_test/upstream.rosinstall
            vcs export --exact ~/ws_upstream/src >> ~/ws_upstream/checksum.txt
      - save_cache:
          key: upstream_ws-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/ws_upstream/src"

