version: 2.1

jobs:
  build:
    docker:
      - image: tylerjw/circle_ci_test-melodic:0.0.1
    environment:
      UPSTREAM_ROSINSTALL: upstream.rosinstall
    working_directory: ~/ws_target
    steps:
      - restore_cache:
          name: Restoring Cache source-v1
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - checkout:
          path: src/circle_ci_test
      - save_cache:
          name: Saving Cache source-v1
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "src/circle_ci_test/.git"


      - restore_cache:
          name: Restoring Cache upstream_ws-v1
          keys:
            - upstream_ws-v1-{{ .Branch }}-{{ .Revision }}
            - upstream_ws-v1-{{ .Branch }}-
            - upstream_ws-v1-
      - run:
          name: Prepare Upstream Workspace
          command: |
            mkdir -p ~/ws_upstream/src
            vcs import ~/ws_upstream/src --shallow --force --input src/circle_ci_test/upstream.rosinstall
      - save_cache:
          name: Saving Cache upstream_ws-v1
          key: upstream_ws-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/ws_upstream/src"

      - run:
          name: Install Upstream Dependencies
          command: rosdep install -q -y --from-paths ~/ws_upstream/src --ignore-src
