# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      ROS_DISTRO: melodic
      ROS_REPO: ros
    working_directory: ~/circle_ci_test
    steps:
      - checkout
      - run:
          name: Checkout industrial_ci
          command: git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
      - run:
          name: Run industrial_ci
          command: .industrial_ci/ci.sh
